
package Forms;


import javax.swing.JOptionPane;
import vendas.vendas;
import vendasDAO.vendasDAO;

public class ViewVendas extends javax.swing.JFrame {

    /**
     * Creates new form ViewRelatorioVendas
     */
    public ViewVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CriarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        EncontrarButton = new javax.swing.JButton();
        RelatorioButton = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtId_cliente = new javax.swing.JTextField();
        txtId_funcionario = new javax.swing.JTextField();
        txtId_veiculo = new javax.swing.JTextField();
        txtData_venda = new javax.swing.JTextField();
        txtValor_venda = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CriarButton.setText("Criar");
        CriarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarButtonActionPerformed(evt);
            }
        });

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        EncontrarButton.setText("Encontrar");
        EncontrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncontrarButtonActionPerformed(evt);
            }
        });

        RelatorioButton.setText("Relatorio");
        RelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioButtonActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Id cliente");

        jLabel3.setText("Id funcionario");

        jLabel4.setText("Id veiculo");

        jLabel5.setText("Data da venda");

        jLabel6.setText("Valor da venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValor_venda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(txtData_venda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId_veiculo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId_funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId_cliente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CriarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AtualizarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExcluirButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RelatorioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EncontrarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 210, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncontrarButton)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarButton)
                    .addComponent(AtualizarButton)
                    .addComponent(RelatorioButton)
                    .addComponent(ExcluirButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarButtonActionPerformed

        int id_cliente = Integer.parseInt(txtId_cliente.getText());
        int id_funcionario = Integer.parseInt(txtId_funcionario.getText());
        int id_veiculo = Integer.parseInt(txtId_veiculo.getText());
        String data_venda = txtData_venda.getText();
        int valor_venda = Integer.parseInt(txtValor_venda.getText());
        
        vendas p = new vendas();
        p.setId_cliente(id_cliente);
        p.setId_funcionario(id_funcionario);
        p.setId_veiculo(id_veiculo);
        p.setData_venda(data_venda);
        p.setValor_venda(valor_venda);
        
       vendasDAO vendasDAO = new vendasDAO();
       vendasDAO.inserir(p);
       
       txtId_cliente.setText("");
       txtId_funcionario.setText("");
       txtId_veiculo.setText("");
       txtData_venda.setText("");
       txtValor_venda.setText("");
    }//GEN-LAST:event_CriarButtonActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed

        int id = Integer.parseInt(txtId.getText());
        int id_cliente = Integer.parseInt(txtId_cliente.getText());
        int id_funcionario = Integer.parseInt(txtId_funcionario.getText());
        int id_veiculo = Integer.parseInt(txtId_veiculo.getText());
        String data_venda = txtData_venda.getText();
        int valor_venda = Integer.parseInt(txtValor_venda.getText());
        
        vendas p = new vendas();
        p.setId(id);
        p.setId_cliente(id_cliente);
        p.setId_funcionario(id_funcionario);
        p.setId_veiculo(id_veiculo);
        p.setData_venda(data_venda);
        p.setValor_venda(valor_venda);

        vendasDAO vendasDAO = new vendasDAO();
        vendasDAO.alterar(p);

       txtId_cliente.setText("");
       txtId_funcionario.setText("");
       txtId_veiculo.setText("");
       txtData_venda.setText("");
       txtValor_venda.setText("");
           
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed

int id = Integer.parseInt(txtId.getText());
vendasDAO vendasDAO = new vendasDAO();
vendasDAO.excluir (id);

txtId_cliente.setText("");
txtId_funcionario.setText("");
txtId_veiculo.setText("");
txtData_venda.setText("");
txtValor_venda.setText("");
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void EncontrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncontrarButtonActionPerformed

        int idPesquisa = Integer.parseInt(txtPesquisa.getText());
vendasDAO vendasDAO = new vendasDAO();
vendas p = vendasDAO.getVendas (idPesquisa);
if(p == null){
   JOptionPane.showMessageDialog(this, "Venda não encontrado"); 
}else{
txtId.setText (String.valueOf(p.getId()));
txtId_cliente.setText (String.valueOf(p.getId_cliente()));
txtId_funcionario.setText (String.valueOf(p.getId_funcionario()));
txtId_veiculo.setText (String.valueOf(p.getId_veiculo()));
txtData_venda.setText (p.getData_venda());
txtValor_venda.setText (String.valueOf(p.getValor_venda()));
    }//GEN-LAST:event_EncontrarButtonActionPerformed
    }
    private void RelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioButtonActionPerformed
        
        ViewRelatorioVendas vrp = new ViewRelatorioVendas();
        vrp.setVisible(true);
    }//GEN-LAST:event_RelatorioButtonActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JButton CriarButton;
    private javax.swing.JButton EncontrarButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JButton RelatorioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtData_venda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId_cliente;
    private javax.swing.JTextField txtId_funcionario;
    private javax.swing.JTextField txtId_veiculo;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtValor_venda;
    // End of variables declaration//GEN-END:variables
}
